[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables should be set in Netlify dashboard, not here
# Go to: Site settings > Environment variables
# Add: VITE_GOOGLE_CLIENT_ID and VITE_GOOGLE_API_KEY
